# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f09c50edb046634d191a6da221b889e37a84c7149754daed705ebca66067b19e273f5648657dd8cec1b3e5066a1439e2f39baad0c4f0048bacf1175efad776a1

test:
  secret_key_base: a4fe1a34e08601c3db05ca0e58047b0afdfa6b8b60a5e7548dff2ffcb6c13b59e9b99cc5bac33df9e5ed016a9577ad61e7f06d2a6171c525b6df7e7212c296e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
